// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "basic_info",
    columns: [
      { name: "Full_name", type: "string", unique: true },
      { name: "Email", type: "email", unique: true },
      { name: "Address", type: "string" },
      { name: "Phone_number", type: "string" },
      { name: "Role", type: "string" },
      { name: "Profile_Photo_Url", type: "string" },
      { name: "Public_id", type: "string" },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "username", type: "string" },
      { name: "password", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type BasicInfo = InferredTypes["basic_info"];
export type BasicInfoRecord = BasicInfo & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type DatabaseSchema = {
  basic_info: BasicInfoRecord;
  users: UsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    " https://Oluwafemi-Akinyemi-s-workspace-fdbhbv.us-east-1.xata.sh/db/basic_info",

  // databaseURL:
  //   "https://Oluwafemi-Akinyemi-s-workspace-fdbhbv.eu-west-1.xata.sh/db/basic_info",
};

// https://Oluwafemi-Akinyemi-s-workspace-fdbhbv.us-east-1.xata.sh/db/basic_info



export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
